### ISSUE TITLE
Overhaul portfolio copy

### ISSUE THREAD

**Issue by dcecile** [dcecile/dcecile-resume-portfolio#15]
### Goals

1. Fill in all areas of the portfolio with clear and concise text
1. Use my "why" to add weight and authenticity to my competitive advantages
1. Evoke these qualities: professional, modern, kind, curious
1. Pass the "human feel" test*

*via [advice from Crew](https://medium.com/who-what-why/why-i-didn-t-look-at-your-resume-2a8ed1f4a5bb):

> _If you apply to a position we’re hiring for, we want to see an email that feels like a human wrote it and says what you’ve done in as a few words as possible._

### Tasks

- [x] Redo intro
- [x] Try out alternate tagline tilde colour
- [x] Move work history to top, and use outro to say "keep reading for"
- [x] Redo work section
- [x] Add making mindset
- [x] Redo mindsets section
- [x] Switch tech intro to explain why and that it's grokking
- [x] Add CI
- [x] Add UI design
- [x] Add version control and bug reporting
- [x] Redo tech fluency section
- [x] Redo side projects section
- [x] Duplicate "find me online" to bottom of portfolio
- [x] Duplicate calls to action to bottom of portfolio
- [x] Fill in all work details
- [x] Fill in all mindset details
- [x] Fill in all tech details
- [x] Fill in all project details
- [x] Run spell check
- [x] Run the [Hemmingway Editor](http://www.hemingwayapp.com/)
- [x] Try marking primary tech with bold
- [x] Consider adding CD
- [x] Consider adding UX
