### ISSUE TITLE
Review resume

### ISSUE THREAD

**Issue by dcecile** [dcecile/dcecile-resume-portfolio#16]
#### Design

1. Draw attention to my name, years of experience, job titles, and tech keywords
1. Raise awareness of my portfolio site
1. Make my contact info easy to find
1. Highlight my side projects and volunteering
1. Evoke these qualities: professional, modern, kind, curious

#### Content

1. Use clear language and short sentences
1. Demonstrate my enthusiasm for learning
1. Demonstrate my leadership qualities
1. Demonstrate my interest in continuous improvement
1. Demonstrate my dedication to interpersonal activities

### Tasks

- [x] Explicitly state resume goals
- [x] Add note for Eagle
- [x] Check spelling and grammar
- [x] Try to improve "view source" copy
- [x] Review with trusted advisor
- [x] De-italicize side projects link URL
- [x] Add "Kitchener, Ontario" location to contacts
- [x] Swap link and tagline
- [x] Change link to say "View my portfolio at"
- [x] Vertically-centre contact info within header
- [x] Reduce link and tagline font size
- [x] Switch co-op date format (use comma)
- [x] Right-align all dates (use leading)
- [x] Make side project names bold (or just not italic)
- [x] Try out non-bold subheaders
- [x] Try to add bullet points for work experience
- [x] Try out sans-serif subheaders
- [x] Fix footer green text (Elm, CSS3) (non-loaded font)
- [x] Review again
- [x] Switch final comma to semicolon
- [x] Try to say co-op education
- [x] Try to pluralize "co-op"
- [x] Try full switch to sans-serif
- [x] Try standardizing icon size
- [x] Switch side projects to match work items (bullet points, keywords at end)
