### ISSUE TITLE
Configure all meta tags

### ISSUE THREAD

**Issue by dcecile** [dcecile/dcecile-resume-portfolio#26]
To show up properly in Google searches for my name, set up meta tags for SEO.

> https://support.google.com/webmasters/answer/7451184?hl=en
> https://support.google.com/webmasters/answer/79812?hl=en

- [x] Write title
- [x] Write description
- [x] Code [social profiles](https://developers.google.com/search/docs/data-types/social-profile)
- [x] Set up Google's search console
- [x] Use search console's HTML Improvements to check if description is too long or too short
- [x] Use search console's [Fetch as Google](https://www.google.com/webmasters/tools/googlebot-fetch) to check Elm rendering
- [x] Use search console's [Structured Data report](https://www.google.com/webmasters/tools/structured-data) and [Rich Cards report](https://www.google.com/webmasters/tools/rich-cards) to check the social profiles

**Comment by dcecile** [comment]
Tags set and Google crawl requested, waiting for results at https://www.google.com/webmasters/tools/dashboard?hl=en&siteUrl=https://dcecile.github.io/

**Comment by dcecile** [comment]
Results look okay, search rank is low (fair) but on the first page for some searches.
